.TH JHD 1 "昭和 63 年 9 月 14 日"
.SH 名前
jhd \- 日本語に対応した 16進数、8進数、アスキー、漢字、かなダンプ
.SH 機能
jhd [ \-abcjkorvO ] [ <file> ] [ +[x|o]<offset>[k] ]
.SH 概要
jhd は、UNIX の od(1) のフォーマットが見にくい（作者にとって）ために
作成されたファイルダンププログラムです。
しかも、もれなく漢字の表示ができるというオマケがついています
（あれ？もれるのかな？そんなことはないはずだが.....）。
.PP
オプションを指定せずに jhd を起動すると、1 行あたり、
16 進数でファイルのオフセットが 8 桁、
ファイルの内容が 2 桁 16 バイト、文字で 16 バイトの表示をしてくれます。
またデータが同じ内容の繰り返しとなる場合は、表示をスキップします。
ファイル名を省略した場合は、標準入力がキーボードの場合には、
Usage メッセージが出力されます。
.PP
オフセットは、“+数字”（10 進数）で指定します。
ファイルの途中から見るのに利用します。
数字の前に“x”をつけると 16 進数、“o”をつけると 8 進数となります。
また数字の後に“k"をつけると、それぞれのオフセット値が 1024 倍されます。
.PP
UNIX 版と OS9 版では、環境変数の“TTYPE”を参照して、
以下のように文字の表示を行ないます（NEWS の OS の仕様にあわせた）。
.TP
mskanji
漢字文字（もちろん ANK を含む）の表示を行ないます。
.TP
jiskanji
mskanjiと同様です。別に、JIS コードで表示を行なうとか、
JIS コードを識別するといった芸はありませんので、あしからず。
.TP
kana
半角カタカナの表示を行ないます。ただし内部コードがEUCのときは、
このモードは存在しません。
.TP
ascii
ASCII キャラクタの表示を行ないます。
TTYPE が設定されていないときも、このモードとなります。
.PP
MS-DOS 版（LSI-C)では、デフォルトで漢字を表示するようになっています。
.PP
以下のオプションがあります。
.TP
\-a
ASCIIキャラクタのみの表示を行ないます（環境変数より優先される）。
.TP
\-b
データの内容をバイト単位の 8 進数で表示します。
.TP
\-c
文字のみを一行 64 バイトで表示します。
.TP
\-j
文字の表示部を、漢字コードに合致するなら、
強制的に漢字で表示します（環境変数より優先される）。
.TP
\-k
文字の表示部を、漢字の表示を禁止して半角カタカナまでとします
（内部コードが Shift-JIS のとき。環境変数より優先される）。
.TP
\-o
データの内容をワード単位の 8 進数で表示します。
バイトオーダーは、システムに依存せず 68000 のようになります。
.TP
\-r
データの内容をワード単位の 8 進数で表示します。
バイトオーダーは、システムに依存せず 8086 のようになります。
.TP
\-v
同じデータの繰り返しのスキップを禁止します。
.TP
\-O
アドレスの表示を 8 進数にします。
.SH 参照
od(1)
.SH 作者
民田雅人 （masat-m@ascii.junet）
