はじめて投稿します。みんみん＠あすきー（アルバイター）です。

（はじめてが、fj.sources というのも豪快かな？）

  NEWS の本や MS-DOS Software-Tools 2 に載っていた jhd を大幅に機能を
拡張し、ほぼ完全に書き換えたのものです。

『機能が増えたよ』と言うと『ちょーだい、mail で送って』の声が多いので、
ここに公開したいと思います。著作権については、無料で配布する限り、どう
していただいてもかまいません。他への転載も自由ですが、あとでバグが出た
りした場合（うーむ、十分とったはずなのだが）は、転載者が責任を持ってそ
の情報を流して下さい。

以下のコンパイルスイッチがありますので、適宜変更して下さい。

	次の三つのうちどれか一つを 1 にする。

UNIX    UNIX 用（特にバージョンには依存しないと思う)
OS9	OS-9/68000 用。ディレクトリのダンプもできます。
	（6809 版でも大丈夫だと思うのだが試していない）
LSI	LSI-C 用 （MS-DOSですよ、CP/Mは使ったことがないので）


EUC	漢字コードがEUCのシステム用。 1 が設定されるとコードの扱いが
	EUCとなる。デフォルトは 0 でシフトJIS 専用。
	誠にすみませんが、NEmacs のように勝手に判断するような器用な
	真似は、私にはできません。またそうすると、表示のモードも用意
	しなくてはならなくなるので。もちろん単なる JIS コードもサポー
	トしていません。なお EUC コードの外字はサポートしておりません。

MS-Cでコンパイルする場合は、LSI-Cのフラグをたてて、標準入力をバイナリー
モードにしている部分を変更するだけで大丈夫のはずです（昔はMSCのフラグも
あった）。X68000 で利用するにも、同様の変更でいけるはずです（実際そうし
て使っています）。

						みんみん＠あすきー
						民田雅人
						masat-m@ascii.junet

P.S.	プログラムを流すのは大変ですね。私も東工大の大野さんと
	同様に思います。
	これを書いてて、ひょっとすると、自分の恥を公開している
	のでは？ という気もしました（そうではないと信じたい）。

P.S. 2  というわけで大野さんごめんなさい。前に差し上げたものは
	バグっています。

P.S. 3  始めて NEmacs と Egg のコンビを使ってみました。実に使
	いやすいと思います。UNIX 上で動くワープロが無い現在、
	これに勝る日本語の入力の環境はないんじゃないかと思いま
	す。

以下は、マニュアルです。

#	This is a shell archive.
#	Remove everything above and including the cut line.
#	Then run the rest of the file through sh.
#----cut here-----cut here-----cut here-----cut here----#
#!/bin/sh
# shar:    Shell Archiver
#	Run the following text with /bin/sh to create:
#	jhd.cat
#	jhd.1
# By:	Jim Omura ()
cat << \SHAR_EOF > jhd.cat

JHD(1)              UNIX Programmer's Manual               JHD(1)

名前
    jhd - 日本語に対応した 16進数、8進数、アスキー、漢字、かなダ
    ンプ

機能
    jhd [ -abcjkorvO ] [ <file> ] [ +[x|o]<offset>[k] ]

概要
    jhd は、UNIX の od(1) のフォーマットが見にくい（作者にとって）
    ために作成されたファイルダンププログラムです。しかも、もれな
    く漢字の表示ができるというオマケがついています（あれ？もれる
    のかな？そんなことはないはずだが.....  ）。

    オプションを指定せずに jhd を起動すると、1 行あたり、16 進数
    でファイルのオフセットが 8 桁、ファイルの内容が 2 桁 16 バイ
    ト、文字で 16 バイトの表示をしてくれます。またデータが同じ内
    容の繰り返しとなる場合は、表示をスキップします。ファイル名を
    省略した場合は、標準入力がキーボードの場合には、Usage メッセ
    ージが出力されます。

    オフセットは、“+数字”（10 進数）で指定します。ファイルの途
    中から見るのに利用します。数字の前に“x”をつけると 16 進数、
    “o”をつけると 8 進数となります。また数字の後に“k"をつける
    と、それぞれのオフセット値が 1024 倍されます。

    UNIX 版と OS9 版では、環境変数の“TTYPE”を参照して、以下の
    ように文字の表示を行ないます（NEWS の OS の仕様にあわせた）。

    mskanji
         漢字文字（もちろん ANK を含む）の表示を行ないます。

    jiskanji
         mskanjiと同様です。別に、JIS コードで表示を行なうとか、
         JIS コードを識別するといった芸はありませんので、あしか
         らず。

    kana 半角カタカナの表示を行ないます。ただし内部コードがEUCの
         ときは、このモードは存在しません。

    ascii
         ASCII キャラクタの表示を行ないます。TTYPE が設定されて
         いないときも、このモードとなります。

    MS-DOS 版（LSI-C)では、デフォルトで漢字を表示するようになっ
    ています。

    以下のオプションがあります。

    -a   ASCIIキャラクタのみの表示を行ないます（環境変数より優先
         される）。

    -b   データの内容をバイト単位の 8 進数で表示します。

    -c   文字のみを一行 64 バイトで表示します。

    -j   文字の表示部を、漢字コードに合致するなら、強制的に漢字
         で表示します（環境変数より優先される）。

    -k   文字の表示部を、漢字の表示を禁止して半角カタカナまでと
         します（内部コードが Shift-JIS のとき。環境変数より優先
         される）。

    -o   データの内容をワード単位の 8 進数で表示します。バイトオ
         ーダーは、システムに依存せず 68000 のようになります。

    -r   データの内容をワード単位の 8 進数で表示します。バイトオ
         ーダーは、システムに依存せず 8086 のようになります。

    -v   同じデータの繰り返しのスキップを禁止します。

参照
    od(1)

作者
    民田雅人 （masat-m@ascii.junet）

バグ
    バグらしき動作が確認された場合は、私（masat-m@ascii.junet）
    まで連絡いただければ、それがバグであると確認された場合は、善
    処したいと思います。
SHAR_EOF
cat << \SHAR_EOF > jhd.1
.TH JHD 1 "昭和 63 年 9 月 14 日"
.SH 名前
jhd \- 日本語に対応した 16進数、8進数、アスキー、漢字、かなダンプ
.SH 機能
jhd [ \-abcjkorvO ] [ <file> ] [ +[x|o]<offset>[k] ]
.SH 概要
jhd は、UNIX の od(1) のフォーマットが見にくい（作者にとって）ために
作成されたファイルダンププログラムです。
しかも、もれなく漢字の表示ができるというオマケがついています
（あれ？もれるのかな？そんなことはないはずだが.....）。
.PP
オプションを指定せずに jhd を起動すると、1 行あたり、
16 進数でファイルのオフセットが 8 桁、
ファイルの内容が 2 桁 16 バイト、文字で 16 バイトの表示をしてくれます。
またデータが同じ内容の繰り返しとなる場合は、表示をスキップします。
ファイル名を省略した場合は、標準入力がキーボードの場合には、
Usage メッセージが出力されます。
.PP
オフセットは、“+数字”（10 進数）で指定します。
ファイルの途中から見るのに利用します。
数字の前に“x”をつけると 16 進数、“o”をつけると 8 進数となります。
また数字の後に“k"をつけると、それぞれのオフセット値が 1024 倍されます。
.PP
UNIX 版と OS9 版では、環境変数の“TTYPE”を参照して、
以下のように文字の表示を行ないます（NEWS の OS の仕様にあわせた）。
.TP
mskanji
漢字文字（もちろん ANK を含む）の表示を行ないます。
.TP
jiskanji
mskanjiと同様です。別に、JIS コードで表示を行なうとか、
JIS コードを識別するといった芸はありませんので、あしからず。
.TP
kana
半角カタカナの表示を行ないます。ただし内部コードがEUCのときは、
このモードは存在しません。
.TP
ascii
ASCII キャラクタの表示を行ないます。
TTYPE が設定されていないときも、このモードとなります。
.PP
MS-DOS 版（LSI-C)では、デフォルトで漢字を表示するようになっています。
.PP
以下のオプションがあります。
.TP
\-a
ASCIIキャラクタのみの表示を行ないます（環境変数より優先される）。
.TP
\-b
データの内容をバイト単位の 8 進数で表示します。
.TP
\-c
文字のみを一行 64 バイトで表示します。
.TP
\-j
文字の表示部を、漢字コードに合致するなら、
強制的に漢字で表示します（環境変数より優先される）。
.TP
\-k
文字の表示部を、漢字の表示を禁止して半角カタカナまでとします
（内部コードが Shift-JIS のとき。環境変数より優先される）。
.TP
\-o
データの内容をワード単位の 8 進数で表示します。
バイトオーダーは、システムに依存せず 68000 のようになります。
.TP
\-r
データの内容をワード単位の 8 進数で表示します。
バイトオーダーは、システムに依存せず 8086 のようになります。
.TP
\-v
同じデータの繰り返しのスキップを禁止します。
.TP
\-O
アドレスの表示を 8 進数にします。
.SH 参照
od(1)
.SH 作者
民田雅人 （masat-m@ascii.junet）
.SH バグ
バグらしき動作が確認された場合は、
私（masat-m@ascii.junet）まで連絡いただければ、
それがバグであると確認された場合は、
善処したいと思います。
SHAR_EOF
#	End of shell archive
exit 0
